# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RestaurantApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'HCSStarRatingView'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'HGCircularSlider'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'CardIO'
  pod 'MRCountryPicker'
  pod 'PushNotifications'
  pod 'SDWebImage'
  pod 'SwiftyGif'
  pod 'JWTDecode', '~> 2.1'
  pod 'SwipeCellKit', '2.4.3'
  # Pods for RestaurantApp

end
